### ISSUE TITLE
Support for n_components==1, others support it. 

### ISSUE THREAD

**Issue by metaheuristic** [DmitryUlyanov/Multicore-TSNE#33] opened 2017-11-11 13:15 UTC
Looks like the failure might be happening in:
Multicore-TSNE/multicore_tsne/tsne.cpp
with this function: evaluateError where it is producing nans. 

Willing to send $100USD in Bitcoin to the first person that can demonstrate a solution before I do.

**Comment by DmitryUlyanov** [comment] 2017-11-17 06:00
Hi, did you manage to resolve it? 

If yes, please send a PR, in no -- I have some time to look at it.

**Comment by metaheuristic** [comment] 2017-11-17 06:35
@DmitryUlyanov I have not resolved it yet, the offer still stands.

**Comment by DmitryUlyanov** [comment] 2017-11-17 14:20
Hi, take a look at this branch. 
https://github.com/DmitryUlyanov/Multicore-TSNE/tree/1d

Now any dimensionality is supported. 

Will be merged to master soon.

**Comment by metaheuristic** [comment] 2017-11-17 20:38
That is great! I'll benchmark it during the next day or so against sklearn
TSNE for accuracy. Once confirmed I'll send you some BTC.

**Comment by DmitryUlyanov** [comment] 2017-12-10 12:29
Looks like will never be confirmed :)

**Closed by DmitryUlyanov** 2017-12-10 12:29 UTC
